#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OpenAccessModels;

namespace OpenAccessModels	
{
	public partial class Unit
	{
		private int _unitID;
		public virtual int UnitID
		{
			get
			{
				return this._unitID;
			}
			set
			{
				this._unitID = value;
			}
		}
		
		private string _unitName;
		public virtual string UnitName
		{
			get
			{
				return this._unitName;
			}
			set
			{
				this._unitName = value;
			}
		}
		
		private IList<Product> _products = new List<Product>();
		public virtual IList<Product> Products
		{
			get
			{
				return this._products;
			}
		}
		
	}
}
#pragma warning restore 1591
