//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ProductId { get; set; }
        public int VendorId { get; set; }
        public string ProductName { get; set; }
        public int UnitId { get; set; }
        public decimal BasePrice { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
