//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ReportId { get; set; }
        public int LocalShopId { get; set; }
        public System.DateTime ReportDate { get; set; }
        public decimal ReportTotalSum { get; set; }
    
        public virtual LocalShop LocalShop { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
