// ********************************
// <autogenerated>
// This is an auto-generated file. Do not edit it.
// Demonstrates the use of T4 templates for file generation.
// In this case an XML file ("Data.xml") is used as a source for the
// names of the classes and their properties.
// </autogenerated>
//
// ********************************
using System;

namespace SampleClasses 
{		 
	public class School
	{
		public string Name { get; set; }
		public string Address { get; set; }
		public int Zip { get; set; }
	}
		 
	public class Teacher
	{
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Subject { get; set; }
	}
		 
	public class Bus
	{
		public string LicensePlate { get; set; }
		public string Driver { get; set; }
	}
}