#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using NorthwindFramework;
using Northwind.Model;


namespace Northwind.Model	
{
	[Table("Categories")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	[Serializable()]
	public partial class Category : NotificationObject
	{
		private int _categoryID;
		[Column("CategoryID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_categoryID")]
		public virtual int CategoryID 
		{ 
		    get
		    {
		        return this._categoryID;
		    }
		    set
		    {
				if (this.CategoryID == value)
				{
					return;
				}
		        this._categoryID = value;
				this.RaisePropertyChanged("CategoryID");
		    }
		}
		
		private string _categoryName;
		[Column("CategoryName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 15, Scale = 0, SqlType = "nvarchar")]
		[Storage("_categoryName")]
		public virtual string CategoryName 
		{ 
		    get
		    {
		        return this._categoryName;
		    }
		    set
		    {
				if (this.CategoryName == value)
				{
					return;
				}
		        this._categoryName = value;
				this.RaisePropertyChanged("CategoryName");
		    }
		}
		
		private string _description;
		[Column("Description", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "ntext")]
		[Storage("_description")]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
				if (this.Description == value)
				{
					return;
				}
		        this._description = value;
				this.RaisePropertyChanged("Description");
		    }
		}
		
		private byte[] _picture;
		[Column("Picture", OpenAccessType = OpenAccessType.LongVarBinary, IsNullable = true, Length = 0, Scale = 0, SqlType = "image")]
		[Storage("_picture")]
		public virtual byte[] Picture 
		{ 
		    get
		    {
		        return this._picture;
		    }
		    set
		    {
				if (this.Picture == value)
				{
					return;
				}
		        this._picture = value;
				this.RaisePropertyChanged("Picture");
		    }
		}
		
		private IList<Product> _products = new List<Product>();
		[Collection(InverseProperty = "Category")]
		[Storage("_products")]
		public virtual IList<Product> Products 
		{ 
		    get
		    {
		        return this._products;
		    }
		}
		
	}
}
