//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.NorthwindDbContextDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_01.NorthwindDbContextDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- --------------------------------------------------
        ///-- Entity Designer DDL Script for SQL Server 2005, 2008, and Azure
        ///-- --------------------------------------------------
        ///-- Date Created: 07/14/2013 20:55:26
        ///-- Generated from EDMX file: F:\Telerik Academy\Databases\Projects\6. Entity Framework\00. Models\Northwind.edmx
        ///-- --------------------------------------------------
        ///
        ///SET QUOTED_IDENTIFIER OFF;
        ///GO
        ///USE [Northwind];
        ///GO
        ///IF SCHEMA_ID(N&apos;dbo&apos;) IS NULL EXECUTE(N&apos;CREATE SCHEMA [dbo]&apos;);
        ///GO
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthwindTwin {
            get {
                return ResourceManager.GetString("NorthwindTwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].[SupplierIncomeByYear]&apos;) and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1)
        ///  drop procedure [dbo].[SupplierIncomeByYear]
        ///GO
        ///
        ///SET QUOTED_IDENTIFIER ON 
        ///GO
        ///
        ///CREATE PROCEDURE SupplierIncomeByYear
        ///@SupplierContactName nvarchar(30),
        ///@BeginningDate datetime, 
        ///@EndingDate datetime
        ///AS
        ///
        ///SELECT Suppliers.ContactName,
        ///	   SUM([Order Subtotals].Subtotal) AS Income
        ///  FROM Orders
        ///  JOIN [Order Subtotals]
        ///    ON Orders.OrderID = [Order Subtota [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupplierIncomeByYear {
            get {
                return ResourceManager.GetString("SupplierIncomeByYear", resourceCulture);
            }
        }
    }
}
