//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringOccurrencesService")]
public interface IStringOccurrencesService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringOccurrencesService/GetOccurrences", ReplyAction="http://tempuri.org/IStringOccurrencesService/GetOccurrencesResponse")]
    int GetOccurrences(string source, string target);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringOccurrencesService/GetOccurrences", ReplyAction="http://tempuri.org/IStringOccurrencesService/GetOccurrencesResponse")]
    System.Threading.Tasks.Task<int> GetOccurrencesAsync(string source, string target);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringOccurrencesServiceChannel : IStringOccurrencesService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringOccurrencesServiceClient : System.ServiceModel.ClientBase<IStringOccurrencesService>, IStringOccurrencesService
{
    
    public StringOccurrencesServiceClient()
    {
    }
    
    public StringOccurrencesServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringOccurrencesServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringOccurrencesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringOccurrencesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetOccurrences(string source, string target)
    {
        return base.Channel.GetOccurrences(source, target);
    }
    
    public System.Threading.Tasks.Task<int> GetOccurrencesAsync(string source, string target)
    {
        return base.Channel.GetOccurrencesAsync(source, target);
    }
}
