#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OpenAccessModels;

namespace OpenAccessModels	
{
	public partial class Group
	{
		private int _groupId;
		public virtual int GroupId
		{
			get
			{
				return this._groupId;
			}
			set
			{
				this._groupId = value;
			}
		}
		
		private string _groupName;
		public virtual string GroupName
		{
			get
			{
				return this._groupName;
			}
			set
			{
				this._groupName = value;
			}
		}
		
		private IList<User> _users = new List<User>();
		public virtual IList<User> Users
		{
			get
			{
				return this._users;
			}
		}
		
	}
}
#pragma warning restore 1591
