SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `bookshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bookshop` ;

-- -----------------------------------------------------
-- Table `bookshop`.`Books`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `bookshop`.`Books` (
  `BookId` INT NOT NULL AUTO_INCREMENT ,
  `BookTitle` VARCHAR(45) NOT NULL ,
  `BookAuthor` VARCHAR(45) NOT NULL ,
  `PublicationDate` DATETIME NULL ,
  `ISBN` VARCHAR(45) NULL ,
  PRIMARY KEY (`BookId`) )
ENGINE = InnoDB;

USE `bookshop` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
