namespace StudentInfo.Enums
{
    public enum University
    {
        Harvard,
        Princeton,
        Yale,
        Columbia,
        UniversityOfChicago,
        MassachusettsInstituteOfTechnology,
        Stanford,
        Duke,
        UniversityOfPennsylvania,
        CaliforniaInstituteOfTechnology,
        DartmouthCollege,
        Northwestern,
        JohnsHopkins,
        WashingtonUniversityInStLouis,
        Brown,
        Cornell,
        Rice,
        UniversityOfNotreDame,
        Vanderbilt,
        Emory,
        Georgetown,
        Berkeley,
        CarnegieMellon,
        UniversityOfCalifornia,
        UniversityOfSouthernCalifornia,
        UniversityOfVirginia,
        WakeForest,
        Tufts,
        UniversityOfMichigan,
        UniversityOfNorthCarolina
    }
}
